name = "AutoAccessorMethods"
uuid = "1c04a6f2-cc8a-4654-b66f-6a97706376ba"
authors = ["harryscholes <harryscholes@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
